#! /bin/sh

#Optimization flags
export CCC_OPTS="-O3 -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard" 

export CCC_OPTS_ADD=-w

COMPILER=gcc
if [ ! -z $1 ] ; then
 COMPILER=$1
fi

if [ -f bench_list ]
then
  benchmarks=`grep -v ^# bench_list`
else
  benchmarks=*  
fi

for i in $benchmarks
do

if [ -d "$i" ] 
then
 tmp=$PWD
 cd $i
 if [ -d "src_work" ] 
 then
  # *** process directory ***
  echo "**********************************************************"
  echo $i
  cd src_work
  chmod +x __compile
  ./__compile $COMPILER
  chmod +x __run
  echo ""
  ls -l a.out 
  echo ""
  # *************************
 fi
 cd $tmp
fi

done

